version: '3'
services:
  deepscholar.front:
    image: nginx
    volumes:
      - ./front/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - deepscholar.client
      - deepscholar.server
    ports:
      - "${DS_FRONT_PORT}:80"
  deepscholar.client:
    volumes:
      - ./client:/root/client
      - /root/client/node_modules/
    image: node:8.1.2
    working_dir: /root/client
    environment:
      - NODE_ENV=development
    depends_on:
      - deepscholar.server
    ports:
      - "${DS_CLIENT_PORT}:3000"
    command: bash -c 'npm i && npm start'
  deepscholar.server:
    volumes:
      - ./server:/root/server
      - ${DS_DATA_DIR}:/root/server/documents
      - /root/server/node_modules/
    image: node:8.1.2
    working_dir: /root/server
    environment:
      - NODE_ENV=development
    depends_on:
      - deepscholar.elasticsearch
      - deepscholar.database
    ports:
      - "${DS_SERVER_PORT}:3001"
    command: bash -c "
      npm i &&
      DEEP_SCHOLAR_URL=${DEEP_SCHOLAR_URL}
      DEEP_SCHOLAR_TOKEN_SECRET=${DEEP_SCHOLAR_TOKEN_SECRET}
      DEEP_SCHOLAR_TOKEN_ISSUER=${DEEP_SCHOLAR_TOKEN_ISSUER}
      DEEP_SCHOLAR_TOKEN_AUDIENCE=${DEEP_SCHOLAR_TOKEN_AUDIENCE}
      OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      npm start"
  deepscholar.database:
    volumes:
      - dbdata:/data/db
    image: mongo:3.6
    environment:
      - MONGO_INITDB_DATABASE=deepscholar
    ports:
      - "${DS_DB_PORT}:27017"
  deepscholar.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${DS_ES_PORT}:9200"
  deepscholar.kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    environment:
      - ELASTICSEARCH_URL=http://deepscholar.elasticsearch:9200
    depends_on:
      - deepscholar.elasticsearch
    ports:
      - "${DS_KIBANA_PORT}:5601"
  deepscholar.elasticsearch-head:
    image: mobz/elasticsearch-head:5
    depends_on:
      - deepscholar.elasticsearch
    ports:
      - "${DS_ESHEAD_PORT}:9100"
volumes:
  dbdata:
    driver: local
  esdata:
    driver: local